package vergeos

import "fmt"

// OIDCApplication is a client that authenticates through VergeOS acting
// as an OpenID Connect identity provider.
//
// ClientSecret is write-only. API responses are accepted and discarded,
// so the field stays empty and printing the application cannot reveal the
// secret. OIDCApplicationService.Create returns the generated secret once,
// as a WriteOnlySecret.
type OIDCApplication struct {
	// Key is the application ID.
	Key FlexInt `json:"$key,omitempty"`
	// Name is the application name.
	Name string `json:"name,omitempty"`
	// Enabled reports whether the application accepts logins.
	Enabled bool `json:"enabled,omitempty"`
	// Created is the creation timestamp (Unix epoch).
	Created int64 `json:"created,omitempty"`
	// Description is an optional description.
	Description string `json:"description,omitempty"`
	// RedirectURI is the allowed callback URLs, separated by newlines.
	RedirectURI string `json:"redirect_uri,omitempty"`
	// ClientID is the generated OAuth client ID.
	ClientID string `json:"client_id,omitempty"`
	// ClientSecret is write-only. It is not encoded or decoded with the
	// application (json:"-"), so a response cannot fill it and logging the
	// application cannot write it. Create returns the generated secret.
	ClientSecret WriteOnlySecret `json:"-"`
	// ForceAuthSource is the auth source used for automatic redirect.
	ForceAuthSource FlexInt `json:"force_auth_source,omitempty"`
	// RestrictAccess limits the application to allowed users and groups.
	RestrictAccess bool `json:"restrict_access,omitempty"`
	// MapUser is the user every successful login is mapped to.
	MapUser FlexInt `json:"map_user,omitempty"`
	// ScopeProfile grants the profile scope.
	ScopeProfile bool `json:"scope_profile,omitempty"`
	// ScopeEmail grants the email scope.
	ScopeEmail bool `json:"scope_email,omitempty"`
	// ScopeGroups grants the groups scope.
	ScopeGroups bool `json:"scope_groups,omitempty"`
	// WellKnownConfiguration is the OIDC discovery URL for this application.
	WellKnownConfiguration string `json:"well_known_configuration,omitempty"`
}

// String prints the application with the client secret redacted.
func (a OIDCApplication) String() string {
	type plain OIDCApplication
	return fmt.Sprintf("%v", plain(a))
}

// GoString prints the application with the client secret redacted.
func (a OIDCApplication) GoString() string {
	type plain OIDCApplication
	return fmt.Sprintf("%#v", plain(a))
}

// Format prints the application with the client secret redacted.
func (a OIDCApplication) Format(f fmt.State, verb rune) {
	type plain OIDCApplication
	formatRedacted(f, verb, plain(a))
}

// OIDCApplicationCreateRequest is the request body for creating an OIDC application.
// client_id and client_secret are generated by VergeOS and are not set here.
type OIDCApplicationCreateRequest struct {
	// Name is the application name (required).
	Name string `json:"name"`
	// Description is an optional description.
	Description string `json:"description,omitempty"`
	// RedirectURI is the allowed callback URLs, separated by newlines.
	// Wildcards are accepted (for example "https://*.example.com/callback").
	RedirectURI string `json:"redirect_uri,omitempty"`
	// Enabled reports whether the application accepts logins.
	// Nil defaults to true when the request is sent.
	Enabled *bool `json:"enabled,omitempty"`
	// ForceAuthSource is the auth source used for automatic redirect.
	// Nil is sent as JSON null. Zero is not a valid row.
	ForceAuthSource *int `json:"force_auth_source"`
	// RestrictAccess limits the application to allowed users and groups.
	RestrictAccess *bool `json:"restrict_access,omitempty"`
	// MapUser is the user every successful login is mapped to.
	// Nil is sent as JSON null. Zero is not a valid row.
	MapUser *int `json:"map_user"`
	// ScopeProfile grants the profile scope. Nil defaults to true.
	ScopeProfile *bool `json:"scope_profile,omitempty"`
	// ScopeEmail grants the email scope. Nil defaults to true.
	ScopeEmail *bool `json:"scope_email,omitempty"`
	// ScopeGroups grants the groups scope. Nil defaults to true.
	ScopeGroups *bool `json:"scope_groups,omitempty"`
}

// OIDCApplicationUpdateRequest is the request body for updating an OIDC application.
// client_id and client_secret cannot be changed.
type OIDCApplicationUpdateRequest struct {
	// Name is the application name.
	Name *string `json:"name,omitempty"`
	// Description is the description.
	Description *string `json:"description,omitempty"`
	// RedirectURI is the allowed callback URLs, separated by newlines.
	RedirectURI *string `json:"redirect_uri,omitempty"`
	// Enabled enables or disables the application.
	Enabled *bool `json:"enabled,omitempty"`
	// ForceAuthSource is the auth source used for automatic redirect.
	ForceAuthSource *int `json:"force_auth_source,omitempty"`
	// RestrictAccess limits the application to allowed users and groups.
	RestrictAccess *bool `json:"restrict_access,omitempty"`
	// MapUser is the user every successful login is mapped to.
	MapUser *int `json:"map_user,omitempty"`
	// ScopeProfile grants the profile scope.
	ScopeProfile *bool `json:"scope_profile,omitempty"`
	// ScopeEmail grants the email scope.
	ScopeEmail *bool `json:"scope_email,omitempty"`
	// ScopeGroups grants the groups scope.
	ScopeGroups *bool `json:"scope_groups,omitempty"`
}

// oidcApplicationListFields are the fields requested when listing OIDC applications.
// client_secret is never requested.
const oidcApplicationListFields = "$key,name,enabled,created,description,redirect_uri,client_id,force_auth_source,restrict_access,map_user,scope_profile,scope_email,scope_groups"

// oidcApplicationGetFields are the fields requested when getting one OIDC application.
// client_secret is not included. well_known_configuration is.
const oidcApplicationGetFields = oidcApplicationListFields + ",well_known_configuration"

// oidcApplicationSecretFields is the projection used once, at creation, to
// read the generated client secret. The secret is returned separately and
// is not stored on OIDCApplication.
const oidcApplicationSecretFields = oidcApplicationGetFields + ",client_secret"
